Replacement = {"traffic": "traffic",
               "trainspotting": "trainspotting",
               "transformersthemovie": "Transformers The Movie",
               "tremors": "tremors",
               "tristanandisolde": "Tristan And Isolde",
               "tron": "tron",
               "tronlegacy": "Tron Legacy",
               "truelies": "True Lies",
               "trumanshowthe": "The Trueman Show",
               "twilightnewmoon": "Twilight New Moon",
               "twinpeaks": "Twin Peaks",
               "twins": "twins",
               "twoforthemoney": "Two For The Money",
               "uglytruththe": "The Ugly Truth",
               "unbreakable": "unbreakable",
               "underfire": "Under fire",
               "unknown": "unknown",
               "up": "up",
               "upintheair": "Up In The Air",
               "uturn": "U Turn",
               "valkyrie": "valkyrie",
               "verdictthe": "The Verdict",
               "verybadthings": "Very Bad Things",
               "vforvendetta": "V For Vandetta",
               "virtuosity": "virtuosity",
               "visitorthe": "The Visitor",
               "wagthedog": "Wag The Dog",
               "walkingtall": "Walking Tall",
               "walktoremembera": "A Walk To Remember",
               "walle": "walle",
               "wallstreet": "Wall Street",
               "wallstreetmoneyneversleeps": "Wall Street Money Nerver Sleeps",
               "warhorse": "War Horse",
               "warmsprings": "Warm springs",
               "waroftheworlds": "War Of The Worlds",
               "warrior": "warrior",
               "waterforelephants": "Water For Elephants",
               "waybackthe": "The Way Back",
               "weownthenight": "We Own The Night",
               "whatliesbeneath": "What Lies Beneath",
               "whenastrangercalls": "What A Stranger Calls",
               "whileshewasout": "While She Was Out",
               "whistleblowerthe": "The Whistle Blower",
               "whitechristmas": "White Christmas",
               "whitejazz": "White Jazz",
               "whiteout": "White Out",
               "whitesquall": "White Squall",
               "whosyourdaddy": "Who's Your Daddy",
               "wildatheart": "Wild At Heart",
               "wildhogs": "Wild Hogs",
               "wildthings": "Wild Things",
               "wildthingsdiamondsintherough": "Wild Things Diamonds In The Rough",
               "wildwildwest": "Wild Wild West",
               "willow": "willow",
               "winwin": "Win Win",
               "witness": "witness",
               "wizardofozthe": "The Wizard Of Oz",
               "wolfofwallstreetthe": "The Wolf Of Wall Street",
               "wonderboys": "Wonder Boys",
               "woodsmanthe": "The Woodsman",
               "worldisnotenoughthe": "The World Is Not Enough",
               "wrestlerthe": "The Wrestler",
               "xfilesfightthefuturethe": "The X-Files Fight The Future",
               "xmen": "X-Men",
               "xxx": "XXX",
               "yesman": "Yesman",
               "youcancountonme": "Yon Can Count On Me",
               "youthinrevolt": "You Thin Revolt",
               "youvegotmail": "You've Got Mail",
               "zerodarkthirty": "Zero Dark Thirty",
               "zerophilia": "zerophilia",
               "starwrsanewhope": "Star Wars A New Hope",
               "starwarsattackoftheclones": "Star Wars Attack Of The Clones",
               "starwarstheempirestrikesback": "Star Wars The Empire Strikes Back",
               "stateandmain": "State And Main",
               "stationwest": "Station West",
               "stepmom": "Stepmom",
               "stingthe": "The Sting",
               "storytelling": "storytelling",
               "strangedays": "Strange Days",
               "strangersonatrain": "Stranger On A Train",
               "stuntmanthe": "The Stuntman",
               "sugar": "sugar",
               "sugarandspice": "Sugar And Spice",
               "sunsetblvd.": "Sunset Boulevard",
               "sunshinecleaning": "Sunshine Cleaning",
               "super8": "Super 8",
               "superbad": "Super Bad",
               "surrogates": "surrogates",
               "sweeneytoddthedemonbarberoffleetstreet": "Sweeney Todd The Demon Barber Of Fleet Street",
               "sweethereafterthe": "The Sweet Herafter",
               "sweetsmellofsuccess": "Sweet Smell Of Sucess",
               "swingers": "swingers",
               "swordfish": "swordfish",
               "syriana": "syriana",
               "takeshelter": "Take Shelter",
               "takinglives": "Taking Lives",
               "takingofpelhamonetwothreethe": "The Taking Of Pelham One Two Three",
               "takingsides": "Taking Sides",
               "talentedmr.ripleythe": "The Talented Mr. Ripley",
               "tallinthesaddle": "Tall In The Saddle",
               "taxidriver": "Taxi Driver",
               "ted": "ted",
               "terminator": "terminator",
               "terminator2judgementday": "Terminator 2 Judgement Day",
               "terminatorsalvation": "Terminator Salvation",
               "thelmalouise": "Thelma Louise",
               "theressomethingaboutmary": "There's Something About Mary",
               "thingthe": "The Thing",
               "thirteendays": "Thirteen Days",
               "thisboyslife": "This Boy's Life",
               "thisis40": "This is 40",
               "thor": "thor",
               "threekings": "Three Kings",
               "threekingsspoilsofwar": "Three King Spoil Of War",
               "threemenandababy": "Three Men And A Baby",
               "thunderbirds": "thunderbirds",
               "thunderheart": "Thunder Heart",
               "ticker": "ticker",
               "timemachinethe": "The Time Machine",
               "tincup": "Tin Cup",
               "tinkertailorsoldierspy": "Tinker Tailor Soldier Spy",
               "tinmen": "Tin Men",
               "tmnt": "Teenage Mutant Ninja Turtles",
               "tombstone": "tombstone",
               "tomorrowneverdies": "Tomorrow nerver dies",
               "tosleepwithanger": "To Sleep With Anger",
               "totalrecall": "Total Recall",
               "touristthe": "The Tourist",
               "scottpilgrimvstheworld": "Scott Pilgrim Vs The World",
               "scream": "scream",
               "scream2": "Scream 2",
               "scream3": "Scream 3",
               "se7en": "se7en",
               "searchersthe": "The Searchers",
               "senseandsensibility": "Sense And Sensibility",
               "serenity": "serenity",
               "serialmom": "Serial Mom",
               "sessionsthe": "The Sessions",
               "seventhsealthe": "The Seventh Seal",
               "sexandthecity": "Sex And The City",
               "sexliesandvideotape": "Six Lies And Video Tape",
               "shakespeareinlove": "Shakespeare In Love",
               "shampoo": "shampoo",
               "shawshankredemptionthe": "The Shawshank Redemption",
               "sherlockholmes": "Sherlock Holmes",
               "shesoutofmyleague": "She's Out Of My League",
               "shifty": "shifty",
               "shiningthe": "The Shining",
               "shippingnewsthe": "The Shipping News",
               "shivers": "shivers",
               "shrek": "shrek",
               "shrekthethird": "Shrek The Third",
               "sideways": "sideways",
               "siegethe": "The Siege",
               "signs": "signs",
               "silenceofthelambs": "Silence Of The Lambs",
               "silverbullet": "Silver Bullet",
               "silverliningsplaybook": "Silver Linings Play Book",
               "simone": "simone",
               "singlewhitefemale": "Single White Female",
               "sisteract": "Sister Act",
               "sixdegreesofseparation": "Six Degrees Of Separation",
               "sixthsensethe": "The Sixth Sense",
               "sleepyhollow": "Sleepy Hollow",
               "slingblade": "Sling Blade",
               "slither": "slither",
               "smashed": "smashed",
               "smokinaces": "Smokin Aces",
               "snatch": "snatch",
               "snowfallingoncedars": "Snow Falling On Cedars",
               "socialnetworkthe": "The Social Network",
               "soimarriedanaxemurderer": "So I Married An Axe Murderer",
               "solaris": "solaris",
               "someonetowatchoverme": "Someone To Watch Over Me",
               "somethingsgottagive": "Somethings Gotta Give",
               "sourcecode": "Source Code",
               "southpark": "southpark",
               "spanglish": "spanglish",
               "spareme": "spareme",
               "spartan": "spartan",
               "sphere": "sphere",
               "spiderman": "spiderman",
               "st.elmosfire": "St.Elmo's Fire",
               "starman": "starman",
               "starshiptroopers": "Starship Troopers",
               "startrek": "startrek",
               "startrekfirstcontact": "Startrek Frist Contact",
               "startrekgenerations": "Startrek Generations",
               "startrekiithewrathofkhan": "Startrek 2 The Wrath Of Khan",
               "startreknemesis": "Startrek Nemesis",
               "startrekthemotionpicture": "Startrek The Motion Picture",
               "starwarsanewhope": "Star Wars A New Hope",
               "pianistthe": "The Pianist",
               "pianothe": "The Piano",
               "pineappleexpress": "Pineapple Express",
               "piratesofthecaribbeandeadmanschest": "Pirate Of The Carabbean Deadman's Chest",
               "pitchblack": "Pitch Black",
               "planetoftheapesthe": "The Planet Of The Apes",
               "platoon": "platoon",
               "pleasantville": "pleasantville",
               "pointbreak": "pointbreak",
               "postmanthe": "The Postman",
               "powerofonethe": "The Power Of One",
               "precious": "precious",
               "predator": "predator",
               "prettywoman": "Pretty Woman",
               "prettywomanfinalscript": "Pretty Womant Final Script",
               "prideandprejudice": "Pride And Prejudice",
               "princessbridethe": "The Princess Bride",
               "privatelifeofsherlockholmesthe": "The Private Life Of Sherlock Holmes",
               "producerthe": "The Producer",
               "programthe": "The Program",
               "prometheus": "prometheus",
               "promnight": "Prom Night",
               "prophecythe": "The Prophecy",
               "psycho": "psycho",
               "pulpfiction": "Plup Fiction",
               "punchdrunklove": "Punch Drunk Love",
               "purplerain": "Purple Rain",
               "quantumproject": "Quantum Project",
               "queenofthedamned": "Queen Of The Damned",
               "ragingbull": "Raging Bull",
               "raisingarizona": "Raising Arizona",
               "ramblingrose": "Rambling Rose",
               "rambofirstbloodiithemission": "Rambo First Blood 2 The Mission",
               "readerthe": "The Reader",
               "rearwindow": "Rear Window",
               "rebelwithoutacause": "Rebel Without A Cause",
               "redridinghood": "Red Riding Hodd",
               "reindeergames": "Reindeer Games",
               "relicthe": "The Relic",
               "rememberme": "Remember Me",
               "replacementsthe": "The Replacements",
               "repoman": "repoman",
               "reservoirdogs": "Reservoir Dogs",
               "residentevil": "Resident Evil",
               "ringu": "ringu",
               "riseoftheguardians": "Rise Of The Guardians",
               "riseoftheplanetoftheapes": "Rise Of The Planet Of The Apes",
               "rko281": "rko281",
               "robinhoodprinceofthieves": "Robin Hood Prince Of Thieves",
               "rocknrolla": "Rock'n'Rolla",
               "rockthe": "The Rock",
               "rocky": "rocky",
               "rockyhorrorpictureshowthe": "The Rocky Horror Picture Show",
               "romeojuliet": "Romeo Juliet",
               "ronin": "ronin",
               "roommatethe": "The Roommate",
               "roughshod": "roughshod",
               "runawaybride": "Runaway Bride",
               "rush": "rush",
               "rushhour": "Rush Hour",
               "rushhour2": "Rush Hour 2",
               "rustandbone": "Rust And Bone",
               "s.darko": "s.darko",
               "saltonseathe": "The Salton Seat",
               "sandlotkidsthe": "The Sandlot Kids",
               "savethelastdance": "Save The Last Dance",
               "savingmr.banks": "Saving Mr. Banks",
               "savingprivateryan": "Saving Private Ryan",
               "saw": "saw",
               "schindlerslist": "Schinlers List",
               "mightymorphinpowerrangersthemovie": "Mighty Morphin Power Rangers The Movie",
               "mimic": "mimic",
               "minisfirsttime": "Mini's First Time",
               "minorityreport": "Minority Report",
               "mirrors": "mirrors",
               "misery": "misery",
               "missionimpossible": "Mission Impossible",
               "missionimpossibleii": "Mission Impossible 2",
               "missiontomars": "Mission To Mars",
               "moneyball": "moneyball",
               "monkeybone": "Monkey Bone",
               "montecarlo": "montecarlo",
               "moon": "moon",
               "moonrisekingdom": "Moon Rise Kingdom",
               "moonstruck": "moonstruck",
               "mrblandingsbuildshisdreamhouse": "Mr. Blanding Builds His Dream House",
               "mrs.brown": "mrs.brown",
               "mud": "mud",
               "mulhollanddrive": "Mulholland Drive", "mumford": "mumford",
               "mummythe": "The Mummy",
               "musicoftheheart": "Music Of The Heart",
               "mutewitness": "Mute Witness",
               "mybestfriendswedding": "My Best Friends Wedding",
               "mygirl": "My Girl",
               "mymotherdreamsthesatansdisciplesinnewyork": "My Mother Dreams The Satans Disciples In New York",
               "mysterymen": "mysterymen",
               "myweekwithmarilyn": "My Week With Marilyn",
               "nashville": "nashville",
               "naturalbornkillers": "Natural Born Killers",
               "newsies": "newsies",
               "newyorkminute": "New York Minute",
               "nextfriday": "Next Friday",
               "nickoftime": "Nick Of Time",
               "nightmareonelmstreeta": "A Nightmare On Elm Street",
               "nightmareonelmstreetthefinalchapter": "A Nighmare On Elm Street Final Chapter",
               "nine": "nine",
               "ninesthe": "The Nines",
               "ninjaassassin": "Ninja Assassin",
               "ninotchka": "ninotchka",
               "nostringsattached": "No Strings Attached",
               "nottinghill": "nottinghill",
               "nursebetty": "Nurse Betty",
               "observeandreport": "Obersce And Report",
               "obsessed": "obsessed",
               "oceanseleven": "Oceans Eleven",
               "oceanstwelve": "Oceans Twelve",
               "oneflewoverthecuckoosnest": "One Flew Over The Cuckoo's Nest",
               "onlygodforgives": "Only God Forgives",
               "ordinarypeople": "Oridnary People",
               "orgyofthedead": "Orgy Of The Dead",
               "otherboleyngirlthe": "The Other Boleyn Gril",
               "outofsight": "Out Of Night",
               "pandorum": "pandorum",
               "panicroom": "Panic Room",
               "papadopoulossons": "Papadopoulos And Sons",
               "paranorman": "paranorman", "pariah": "pariah",
               "patriotthe": "The Patriot",
               "paul": "paul",
               "pearlharbor": "pearlharbor",
               "peepingtom": "Peeping Tom",
               "peggysuegotmarried": "Peggy Sue Got Married",
               "perfectcreature": "Prefect Creature",
               "perfectworlda": "A Perfect World",
               "perksofbeingawallflowerthe": "The Perks Of Being A Wall Flower",
               "petsematary": "Pet Sematary",
               "petsemataryii": "Pet Sematary 2",
               "philadelphia": "philadelphia",
               "phonebooth": "phonebooth",
               "pi": "pi",
               "Liolnlawyerthe": "The Lincoln Lawyer",
               "littleathens": "Little Athens",
               "littlenicky": "Little Nicky",
               "livinginoblivion": "Living In Oblivion",
               "lonestar": "lonestar",
               "longkissgoodnightthe": "The Long Kiss Good Night",
               "looper": "looper",
               "lordofillusions": "Lord Of illusions",
               "lordoftheringsfellowshipoftheringthe": "Lord Of The Rings Fellowship Of The Ring",
               "lordoftheringsreturnoftheking": "Lord Of The Rings Return Of The King",
               "lordoftheringsthetwotowers": "Lord Of The Ring The Two Towers",
               "lordofwar": "Lord Of War",
               "losersthe": "The Losers",
               "losthighway": "Lost Highway",
               "lostinspace": "Lost In Space",
               "lostintranslation": "Lost In Translation",
               "loveandbasketball": "Love And Basketball",
               "machete": "machete",
               "machinegunpreacher": "Machinegun Preacher",
               "magnolia": "magnolia",
               "majesticthethebijou": "The Majestic The Bijou",
               "majorleague": "Major League",
               "malcolmx": "Malcolm X",
               "malibusmostwanted": "Malibu's Most Wanted",
               "manchuriancandidatethe": "The Manchurian Candidate",
               "manhattanmurdermystery": "Manhattan Murder Mystery",
               "manhunter": "Man Hunter",
               "manintheironmask": "Man In The Iron Mask",
               "manonfire": "Man On Fire",
               "manonthemoon": "Man On The Moon",
               "mantrouble": "Man Trouble",
               "manwhoknewtoomuchthe": "The Man Who Knew Too Much",
               "manwhowasnttherethe": "The Man Who Wasn'tThere",
               "margaret": "margaret",
               "margincall": "Margin Call",
               "margotatthewedding": "Margot At The Wedding",
               "mariachiel": "El Mariachi",
               "marleyme": "Marly And me",
               "marthamarcymaymarlene": "Martha Marry May Marlene",
               "marty": "marty",
               "masterandcommander": "Master And commander",
               "masterthe": "The Master",
               "matrixthe": "TheMatrix",
               "maxpayne": "Max Payne",
               "meanstreets": "Mean Streets",
               "meetjoeblack": "Meet Joe Black",
               "meetjohndoe": "Meet John Doe",
               "megamind": "megamind",
               "memento": "memento",
               "meninblack": "Men In Black",
               "meninblack3": "Men In Black 3",
               "metro": "metro",
               "miamivice": "Miami Vice",
               "midnightcowboy": "Midnight Cowboy",
               "midnightexpress": "Midnight Express",
               "invictus": "invictus",
               "islandthe": "The Island",
               "istillknowwhatyoudidlastsummer": "I Still Know What You Did Last Summer",
               "italianjobthe": "The Italian Job",
               "itsawonderfullife": "It's A Wonderful Life",
               "itscomplicated": "It's Complicated",
               "jacketthe": "The Jacket",
               "jackiebrown": "Jackie Brown",
               "jacobsladder": "Jacobs Ladder",
               "janeeyre": "Jane Eyre",
               "jasonx": "Jason X",
               "jaws": "jaws", "jaws2": "Jaws 2",
               "jayandsilentbobstrikeback": "Jay and Silent Bob Strike Back",
               "jennifereight": "Jennifer 8",
               "jennifersbody": "Jennfier's Body",
               "jerrymaguire": "Jerry Maguire",
               "jfk": "jfk",
               "jimmyandjudy": "Jimmy And Judy",
               "judgedredd": "Jude Dredd",
               "juno": "juno",
               "jurassicpark": "Jurassic Park",
               "jurassicparkiii": "Jurassic Park 3",
               "jurassicparkthelostworld": "Jurassic Park The Lost World",
               "kafka": "kafka",
               "kalifornia": "kalifornia",
               "kateleopold": "Kate Leopold",
               "kidsareallrightthe": "The Kids Are All Right",
               "killbillvolume12": "Kill Bill Volume 12",
               "killingzoe": "Killing Zoe",
               "kingdomthe": "The Kingdom",
               "kingkong": "King Kong",
               "kingofcomedythe": "The King Of Comedy",
               "kingsspeechthe": "The Kings Speech",
               "klute": "klute",
               "knockedup": "Knocked Up",
               "kramervskramer": "Kramer Vs Kramer",
               "kundun": "kundun",
               "kungfupanda": "Kungfu Panda",
               "l.a.confidential": "L.A. Confiential",
               "laboroflove": "Labor Of Love",
               "ladykillersthe": "The Lady Killers",
               "lakeplacid": "Lake Placid",
               "landofthedead": "Land Of The Dead",
               "larrycrowne": "Larry Crowne",
               "lastboyscoutthe": "The Last Boyscout",
               "lastchanceharvey": "Last Chance Harvey",
               "lastflightthe": "The Last Flight",
               "lastofthemohicansthe": "The Last Of The Mohicans",
               "laststationthe": "The Last Station",
               "lasttangoinparis": "Last Tango in Paris",
               "lawabidingcitizen": "Law Abiding Citizen",
               "leavinglasvegas": "Leaving Las Vegas",
               "legallyblonde": "Legally Blonde",
               "legion": "legion",
               "lesmiserables": "Les Miserables (1998)",
               "leviathan": "leviathan",
               "liarliar": "Liar Liar",
               "life": "life",
               "lifeasahouse": "Life As A House",
               "lifeofdavidgalethe": "The Life Of David Gale",
               "lifeofpi": "Life Of Pi",
               "lightsleeper": "Light Sleeper",
               "limeythe": "The Limey",
               "limitless": "limitless",
               "hellraiserhellseeker": "Heall Raiser Hell Seeker",
               "helpthe": "The Help",
               "henryfool": "Henry Fool",
               "henryscrime": "Henry's Crime",
               "hesher": "hesher",
               "hesjustnotthatintoyou": "He's Just Not That Into You",
               "highfidelity": "High Fidelity",
               "highlander": "High Lander",
               "hillshaveeyesthe": "The Hills Have Eyes",
               "hisgirlfriday": "His Girl Friday",
               "hitchcock": "hitchcock",
               "hollowman": "hollowman",
               "honeydripper": "Honey Dripper",
               "horriblebosses": "Horrible Bosses",
               "horsewhispererthe": "The Horse Whisperer",
               "hospitalthe": "The Hospital",
               "hostage": "hostage",
               "hotelrwanda": "Hotel Rwanda",
               "hottubtimemachine": "Hottub Time Machine",
               "houseof1000corpses": "House Of 1000 Corpses",
               "howtolosefriendsalienatepeople": "How To Lose Friends Alienate People",
               "howtotrainyourdragon": "How To Train Your Dragon",
               "howtotrainyourdragon2": "How To Train Your Dragon 2",
               "hudsonhawk": "Hudson Hawk",
               "hudsuckerproxythe": "The Hud Sucker Porxy",
               "humannature": "Human Nature",
               "huntforredoctoberthe": "The Hunt For Red October",
               "iamnumberfour": "I Am Number Four",
               "iamsam": "I Am Sam",
               "icestormthe": "The Ice Strom",
               "idesofmarchthe": "The Ides Of March",
               "illdoanything": "I'll Do Anything",
               "iloveyouphillipmorris": "I Love You Phillip Morris",
               "independenceday": "Independence Day",
               "indianajonesandthelastcrusade": "Indiana jones And The Last Crusade",
               "indianajonesandtheraidersofthelostark": "Indiana Jones And The Raider Of The Lost Ark",
               "indianajonesandthetempleofdoom": "Indiana Jones And The Temple Of Doom",
               "indianajonesiv": "Indiana Jones 4",
               "informantthe": "The Informant",
               "inglouriousbasterds": "Inglourious Basterds",
               "insiderthe": "The Insider",
               "insidious": "insidious",
               "insomnia": "insomnia",
               "interviewwiththevampire": "Interview With The Vampire",
               "inthebedroom": "Ine The Bedroom",
               "intheloop": "In The Loop",
               "intolerablecruelty": "Intolerable Cruelty",
               "intothewild": "Into The Wild",
               "inventingtheabbotts": "Inventing The Abbotts",
               "inventionoflyingthe": "The Invention Of Flying",
               "ghostworld": "Ghost World",
               "gingersnaps": "Ginger Snaps",
               "girlwiththedragontattoothe": "The Girl With The Dragon Tattoo",
               "gladiator": "gladiator",
               "glengarryglengross": "Glen Garry Glen Gross",
               "godfather": "godfather",
               "godfatherpartii": "Godfather Part 2",
               "godfatherpartiiithe": "The Godfather Part 3",
               "godsandmonsters": "Gods And Monsters",
               "godzilla": "godzilla",
               "gonein60seconds": "Gone In 60 Seconds",
               "goodgirlthe": "The Good Girl",
               "goodwillhunting": "Good Will Hunting",
               "gothika": "gothika",
               "graduatethe": "Ther Graduate",
               "grandhotel": "Grand Hotel",
               "grandtheftparsons": "Grand Theft Parsons",
               "grantorino": "Gran Torino",
               "grapesofwraththe": "The Grapes Of Wrath",
               "gravity": "gravity",
               "greenmilethe": "The Green Mile",
               "gremlins": "gremlins",
               "gremlins2": "Gremlins 2",
               "griftersthe": "The Grifters",
               "grossepointblank": "Gross Point Blank",
               "groundhogday": "Groundhog Day",
               "hackers": "hackers",
               "halloweenthecurseofmichaelmyers": "Halloween The Curse Of Michael Myers",
               "hallpass": "Hall Pass",
               "hancock": "hancock",
               "hangoverthe": "The Hangover",
               "hanna": "hanna",
               "hannahandhersisters": "Hannah And Her Sisters",
               "hannibal": "hannibal",
               "happybirthdaywandajune": "Happy Birthday Wanda June",
               "happyfeet": "Happy Feet",
               "hardrain": "Hard Rain",
               "hardtokill": "Hard To Kill",
               "haroldandkumargotowhitecastle": "Harold & Kumar Go to White Castle",
               "hauntingthe": "The Haunting",
               "heat": "heat",
               "heathers": "heathers",
               "heavymetal": "Heavy Metal",
               "hebrewhammerthe": "The Hebrew Hammer",
               "heist": "heist",
               "hellboundhellraiserii": "Hell Bound Hell Raiser 2",
               "hellboy": "Hell Boy",
               "hellboy2thegoldenarmy": "Hell Boy 2 The Golden Army",
               "hellraiser": "Hell Raiser",
               "hellraiser3hellonearth": "Hell Raiser 3 Hell On Earth",
               "hellraiserdeader": "Heall Raiser Deader",
               "evildeadiideadbydawn": "Evil Dead 2 Dead By Dawn",
               "excalibur": "excalibur",
               "existenz": "existenz",
               "extract": "extract",
               "fabulousbakerboysthe": "The Fabulous Baker Boys",
               "faceoff": "Face Off",
               "fairgame": "Fair Game",
               "familymanthe": "The Familyman",
               "fantasticfour": "Fantistic Four",
               "fantasticmrfox": "Fantastic Mr.Fox",
               "fargo": "fargo",
               "fasttimesatridgemonthigh": "Fast Time At Ridgemont High",
               "fatalinstinct": "Fata Instinct",
               "faultinourstarsthe": "The Fault In Ours Stars",
               "fearandloathinginlasvegas": "Fear And Loathing In Las Vegas",
               "feast": "feast",
               "ferrisbuellersdayoff": "Ferris Bueller's Day Off",
               "fieldofdreams": "Fiel Of Dreams",
               "fifthelementthe": "The Fifth Element",
               "fightclub": "Fight Club",
               "fighterthe": "The Fighter",
               "finaldestination": "Final Destination",
               "finaldestination2": "Final Destination 2",
               "fiveeasypieces": "Five easy Pieces",
               "flashgordon": "Flash Gordon",
               "flight": "flight",
               "flintstonesthe": "The FlintStones",
               "forrestgump": "forrestgump",
               "fourrooms": "Four Rooms",
               "fracture": "fracture",
               "frances": "frances",
               "frankenstein": "frankenstein",
               "freaked": "freaked",
               "freddyvs.jason": "Freddy Vs Jason",
               "frenchconnectionthe": "The French Connection",
               "frequency": "frequency",
               "fridaythe13th": "Friday The 13th",
               "fridaythe13thpartviiijasontakesmanhattan": "Friday The 13th Part 8 Jason Takes Manhattan",
               "fromdusktilldawn": "From Dusk Till Dawn",
               "fromheretoeternity": "From Herre To Eternity",
               "frozen": "frozen",
               "frozendisney": "Frozen Disney",
               "frozenriver": "Frozen River",
               "fruitvalestation": "Fruitvale Station",
               "fugitivethe": "The Fugitive",
               "g.i.jane": "G. I. Jane",
               "gamer": "gamer",
               "gamethe": "The Game",
               "gandhi": "gandhi",
               "gangrelated": "Gang Related",
               "gattaca": "gattaca",
               "getawaythe": "The Getaway (1972)",
               "getcarter": "Get Carter",
               "getlow": "Get Low",
               "ghost": "ghost",
               "ghostbusters": "Ghost Busters",
               "ghostbusters2": "Ghost Buster 2",
               "ghostrider": "Ghost Rider",
               "defiance": "defiance",
               "departedthe": "The Departed",
               "descendantsthe": "The Descendants",
               "despicableme2": "Despicable Me 2",
               "detroitrockcity": "Detroit Rock City",
               "devilinabluedress": "Devil In A Blue Dress",
               "devilsadvocate": "Devil's Advocate",
               "diehard": "Die Hard",
               "diehard2": "Die Hard 2",
               "diner": "diner",
               "distinguishedgentlemanthe": "The Distinguished Gentlemna",
               "disturbia": "disturbia",
               "djangounchained": "Django Unchained",
               "donniebrasco": "Donnie Brasco",
               "doorsthe": "The Doors",
               "dotherightthing": "Do The Right Thing",
               "doubleindemnity": "Double Indemnity",
               "dragmetohell": "Drag Me To Hell",
               "dragonslayer": "Dragon Slayer",
               "drive": "drive",
               "driveangry": "Drive Angry",
               "dropdeadgorgeous": "Drop Dead Gorgeous",
               "drywhiteseasona": "Dry White Seasons",
               "ducksoup": "ducksoup",
               "dumbanddumber": "Dumb And Dumber",
               "dune": "dune",
               "eagleeye": "Eagle Eye",
               "easternpromises": "Eatern Promises",
               "easya": "easya",
               "edtv": "Ed TV",
               "edwardscissorhands": "Edward Scissor Hands",
               "edwood": "edwood",
               "election": "election",
               "elephantmanthe": "The Elephantman",
               "elizabeththegoldenage": "Elizabeth The Golden Age",
               "enemyofthestate": "Enemy Of The State",
               "englishpatientthe": "The English Patient",
               "enough": "enough",
               "entrapment": "entrapment",
               "eriktheviking": "Erik The Viking",
               "erinbrockovich": "Erin Brokovich",
               "escapefroml.a.": "Escape From L.A.",
               "escapefromnewyork": "Esacape From New York",
               "eternalsunshineofthespotlessmind": "Eternal Sunshine Of the Spotless Mind",
               "evencowgirlsgettheblues": "Even Cowgirl Get The Blues",
               "clashofthetitans": "Clash Of The Titan",
               "clerks": "clerks",
               "cliffhanger": "Cliff Hanger",
               "clueless": "clueless",
               "cobb": "cobb",
               "codeofsilence": "Code Of Silence",
               "coldmountain": "Cold Mountain",
               "collateraldamage": "Collateral Damage",
               "colombiana": "colombiana",
               "colorofnight": "Color Of Night",
               "commando": "commando",
               "conanthebarbarian": "Conan the Barnarian",
               "confessionsofadangerousmind": "Confessions Of A Dangerous Mind",
               "constantine": "constantine",
               "coolerthe": "The Cooler",
               "copycat": "copycat",
               "coraline": "coraline",
               "coriolanus": "Corio Lanus",
               "cowboysaliens": "Cowboys aliens",
               "cradle2thegrave": "Crad 2 The Graves",
               "crank": "crank",
               "crash": "crash",
               "crazylove": "Crazy Love",
               "crazystupidlove": "Crazy Stupid Love",
               "creation": "creation",
               "crimespree": "Crime Spree",
               "croodsthe": "The Croods",
               "crouchingtigerhiddendragon": "Crouching Tiger Hidden Dragon",
               "croupier": "croupier",
               "crowcityofangelsthe": "The Crow City Of Angel",
               "crowsalvationthe": "The Crow Salvation",
               "crowthe": "The Crow",
               "cruelintentions": "Cuel Intentions",
               "cryinggame": "Crying Game",
               "cube": "cube",
               "curiouscaseofbenjaminbuttonthe": "The Curious Case Of benjamin Button",
               "custody": "custody",
               "damnedunitedthe": "The Damned United",
               "danceswithwolves": "Dance Wiht Wolves",
               "darkcity": "Dark City",
               "darkknightrisesthe": "The Dark Night Rises",
               "darkman": "darkman",
               "darkstar": "Dark Star",
               "datenight": "Date Night",
               "davebarryscompleteguidetoguys": "Dave Barrys Complete Guide To Guys",
               "dayofthedead": "Day Of The Dead",
               "daysofheaven": "Days Of Heaven",
               "daytheclowncriedthe": "The Day The Clown Cried",
               "daytheearthstoodstillthe": "The Day The earth stoods Still",
               "deadpoetssociety": "Dead Poets society",
               "deathatafuneral": "Death At aA Funeral",
               "deathtosmoochy": "Death To Smoochy",
               "debtthe": "The Debt",
               "deception": "deception",
               "deepcover": "Deep Cover",
               "deeprising": "Deep Rising",
               "bones": "bones",
               "bonfireofthevanities": "Bonfire Of The vanities",
               "bonnieandclyde": "Bonnie And Clyde",
               "boogienights": "Boogie Nights",
               "bookofelithe": "The Book Of Eli",
               "boondocksaints2allsaintsday": "Boondock Saints 2 All Saint's Day",
               "boondocksaintsthe": "The Boondock Saints ",
               "bottlerocket": "Bottler Rocket",
               "bound": "bound",
               "bountyhunterthe": "The Bounty Hunter",
               "bourneidentitythe": "The Bourne Indentity",
               "bourneultimatumthe": "The Bourne Ultimatum",
               "boxthe": "The box",
               "braveheart": "Brave Heart",
               "brazil": "brazil",
               "breakdown": "breakdown",
               "breakfastclubthe": "The Breakfast Club",
               "breakingaway": "Breaking Away",
               "brick": "brick",
               "bridesmaids": "Brides Maids",
               "bringingoutthedead": "Bringing Out The Dead",
               "broadcastnews": "Broad Cast News",
               "brokenembraces": "Broken Embraces",
               "brothersbloomthe": "THe Brothers Bloom",
               "brucealmighty": "Bruce Almighty",
               "buffythevampireslayer": "Buff The Vampire Slayer",
               "bulldurham": "Bull Durham", "buried": "buried",
               "burlesque": "burlesque",
               "burnafterreading": "Burn After Reading",
               "burningannie": "Burning Annie",
               "butterflyeffectthe": "The Butterfly Effect",
               "candletowater": "Candle To Water",
               "capote": "capote",
               "carrie": "carrie",
               "cars2": "Cars 2",
               "case39": "Case 39",
               "casino": "casino",
               "castaway": "Cast Away",
               "catchmeifyoucan": "Catch Me If You can",
               "toystory": "Toy Story",
                "midnightinparis": "Midnight in Paris",
                "ghostship": "Ghost Ship",
                "eventhorizon": "Event Horizon",
                "deerhunterthe": "The Deer Hunter",
                "cecilb.demented": "Cecil B. Demented",
                "cedarrapids": "Cedar Rapids",
                "celestejesseforever": "Celeste Jesse Forever",
                "cellthe": "The Cell",
                "changeupthe": "The Change Up",
                "charliesangels": "Charlie's Angels",
                "chasingamy": "Chasing Amy",
                "chasingsleep": "Chasing Sleep",
                "cherryfalls": "Cherry Falls",
                "christcomplex": "Christ Complex",
                "chroniclesofnarniathelionthewitchandthewardrobe": "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
                "ciderhouserulesthe": "The Cider House Rules",
                "cincinnatikidthe": "The Cinciannati Kid",
                "cinemaparadiso": "Cinema Paradiso",
                "cirquedufreakthevampiresassistant": "Cirque Du Freak The Vampire Assistant",
                "citizenkane": "Citizen Kane",
                "cityofjoy": "City Of Joy",
                "autumninnewyork": "Autumn In New York",
                "avengersthe": "The Avengers",
                "avengersthe2012": "The Avangers 2012",
                "avventuraltheadventure": "L'Avventura The Adventure",
                "bachelorparty": "Bachelor Party",
                "bachelorpartythe": "The Bachelor Party",
                "backupplanthe": "The Back-up Plan",
                "badboys": "Bad Boys",
                "badcountry": "Bad Country",
                "baddayatblackrock": "Bad Day At Black Rock",
                "baddreams": "Bad Dreams",
                "badlands": "Badlands (1973)",
                "badlieutenant": "Bad Lieutenant",
                "badsanta": "Bad Santa",
                "badteacher": "Bad Teacher",
                "barrylyndon": "Barry Lyndon",
                "bartonfink": "Barton Fink",
                "basicinstinct": "Basic Instinct",
                "batman2": "Batman 2",
                "battleofalgiersthe": "The Battle Of Algiers",
                "battleofshakerheightsthe": "The Battle Of Shaker Heights",
                "beastsofthesouthernwild": "Beast Of The Southern Wild",
                "beavisandbuttheaddoamerica": "Beavis And Butt-Head Do America",
                "beinghuman": "Being Human",
                "beingjohnmalkovich": "Being John Malkovich",
                "beingthere": "Being There",
                "believerthe": "The Beliver",
                "bestexoticmarigoldhotelthe": "The Best Exotic Marigold Hotel",
                "bigbluethe": "The Big Blue",
                "bigfish": "Big Fish",
                "biglebowskithe": "The Big Lewbowski",
                "bigwhitethe": "The Big White",
                "birdsthe": "The Birds",
                "birthdaygirl": "Birthday Girl",
                "blackdahliathe": "The Black Dahlia",
                "blackrain": "Black Rain",
                "blacksnakemoan": "Black Snake Moan",
                "blackswan": "Black Swan",
                "bladeii": "Blade 2",
                "bladerunner": "Blade Runner",
                "bladetrinity": "Blade Trinity",
                "blastfromthepastthe": "The Blast From The Past",
                "blindsidethe": "The Blind Side",
                "blingringthe": "The Bling Ring",
                "bloodandwine": "Blood And Wine",
                "bloodsimple": "Blood Simple",
                "bluevalentine": "Blue Valentine",
                "bluevelvet": "Blue Velvet",
                "bodiesrestmotion": "Bodies Rest And Motion",
                "bodyheat": "Body Heat",
                "500daysofsummer": "500 Days Of Summer",
                "5050": "50/50",
                "abovethelaw": "Above The Law",
                "absolutepower": "Absolute Power",
                "abyssthe": "The Abyss",
                "aceventurapetdetective": "Ace Ventura Pet Detective",
                "addamsfamilythe": "The Addams Family",
                "adjustmentbureauthe": "The Adjustment Bureau",
                "afewgoodmen": "A Few Good Men",
                "after.life": "After.Life",
                "afterschoolspecial": "After School Special",
                "agnesofgod": "Agnes Of God",
                "airforceone": "Air Force One",
                "airplane": "Airplane",
                "airplane2thesequel": "Airplane 2 The Squel",
                "aliennation": "Alien Nation",
                "allabouteve": "All About Eve",
                "allaboutsteve": "All about Steve",
                "allthekingsmen": "All The King's Men",
                "allthepresidentsmen": "All The President's Men",
                "almostfamous": "Almost Famous",
                "aloneinthedark": "Alone In The Dark",
                "americanbeauty": "American Beauty",
                "americangangster": "American Gangster",
                "americangraffiti": "American Graffiti",
                "americanhustle": "American Hustle",
                "americanmadness": "American Madness",
                "americanpie": "American Pie",
                "americanpresidentthe": "The American President",
                "americanshaolinkingofkickboxersii": "American Shaolin: King Of Kickboxers 2",
                "americansplendor": "American Splendor",
                "americanthe": "The American",
                "americanwerewolfinlondon": "American Werewolf In London",
                "amityvilleasylumthe": "The Amityville Asylum",
                "analyzethat": "Analyze That",
                "analyzethis": "Analyze This",
                "aneducation": "An Education",
                "angeleyes": "Angel Eyes",
                "angelsdemons": "Angels And Demons",
                "annakarenina": "Anna Karenina",
                "anniehall": "Annie Hall",
                "anniversarypartythe": "The Anniversary Party",
                "apartmentthe": "The Apartment",
                "apocalypsenow": "Apocalypse Now",
                "aprilfoolsday": "Aprilfool's Day",
                "aptpupil": "Apt Pupil",
                "arcticblue": "Arctic Blue",
                "armyofdarkness": "Army Of Darkness",
                "arsenicandoldlace": "Arsenic And Old Lace",
                "asgoodasitgets": "As Good As It Gets",
                "assignmentthe": "The Assignment",
                "augustosagecounty": "August: Osage County",
                "austinpowersinternationalmanofmysteryAndthespywhoshaggedme": "Austin Powers: International Man of Mystery",
                "authorsanonymous": "Authors Anonymous",
                "10thingsihateaboutyou": "10 Things I Hate About You",
                "127hours": "127 Hours",
                "12andholding": "12 And Holding",
                "12monkeys": "12 Monkeys",
                "12yearsaslave": "12 Years A Slave",
                "1492conquestofparadise": "1492 Conquest Of Paradise",
                "15minutes": "15 Minutes",
                "17again": "17 Again",
                "2001aspaceodyssey": "2001 A Space Odyssey",
                "30minutesorless": "20 Minutes Or Less"}
